name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4  
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pruebatecnica:latest 

      - name: Export environment variables
        run: |
          echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
          echo "AWS_INGESTION_KEY=${{ secrets.AWS_INGESTION_KEY }}" >> $GITHUB_ENV
          echo "AWS_INGESTION_SECRET_KEY=${{ secrets.AWS_INGESTION_SECRET_KEY }}" >> $GITHUB_ENV
          echo "AWS_PROCESSING_KEY=${{ secrets.AWS_PROCESSING_KEY }}" >> $GITHUB_ENV
          echo "AWS_PROCESSING_SECRET_KEY=${{ secrets.AWS_PROCESSING_SECRET_KEY }}" >> $GITHUB_ENV

      - name: Deploy services
        run: |
          docker-compose up -d
